### ISSUE TITLE
Guidance around using confidential data

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-opensci/nmfs-connect#21]
Users could benefit from guidance on how (if at all) confidential data should be used on Posit connect.

**Comment by erinsteiner-NOAA** [comment]
Notes from the Posit spaces discussion:

- The AWS server that our posit connect instance is on is fedramp certified, but posit itself is not
- GitHub Enterprise is fedramp certified, but our Authorization To Use for GitHub Enterprise Cloud does not authorize hosting confidential data on our instance
- NWFSC model is to do all confidential data processing within the locally hosted github instance and then only push pre-aggregated (non-confidential) information into Posit Connect

**Comment by k-doering-NOAA** [comment]
We don't have guidance about how to use confidential data, so our best guidance currently is not to use it or process confidential data, regardless of if the product is private, noaa internal, or public. We suggest:
- processing data locally/elsewhere so it is summarized enough to not be confidential (rule of 3s)
- pushing only summarized data to Posit connect
- using summarized data in products

I will add this point to the Posit connect user guide, and we can update if we learn about ways to use confidential data that are OK on posit connect.

**Comment by k-doering-NOAA** [comment]
Adyan's [Confidentiality-Confidence-Builder](https://github.com/nmfs-opensci/Confidentiality-Confidence-Builder) is a great resource for learning to work with confidential data.
