### ISSUE TITLE
DEPENDENCY REQUEST: R version not updated on https://dev-connect.fisheries.noaa.gov/

### ISSUE THREAD

**Issue by galuardi** [nmfs-opensci/nmfs-connect#32]
##  R 4.3.6 upgraded to R 4.4 (latest) 

```
The command failed with output:
ERROR: this R is version 4.3.2, package 'MASS' requires R >= 4.4.0
```

It was my understanding that we all needed to upgrade R to the latest version due to a vulnerability in previous versions. I've done so but now the app won't deploy on the dev instance.

**Comment by k-doering-NOAA** [comment]
Thanks @galuardi! This request to add R 4.4.0 has been added: https://apps-st.fisheries.noaa.gov/jira/browse/NPCG-9

**Comment by k-doering-NOAA** [comment]
@galuardi could you try deploying again? R 4.4.0 has now been added to dev.

**Comment by galuardi** [comment]
redeployment was successful. thanks everyone!

**Comment by k-doering-NOAA** [comment]
@galuardi thanks for confirming!
