### ISSUE TITLE
Can we disable the require login?

### ISSUE THREAD

**Issue by erinsteiner-NOAA** [nmfs-opensci/nmfs-connect#5]
At our meeting today, we discussed the issue with leaving the "auto-add" for new users turned on. I'm wondering if we can change the default settings for new apps so that we can disable the "All users - login required" option: https://community.rstudio.com/t/disable-functionality-of-choosing-anyone-no-login-required-in-rstudio-connect/68361/2

**Comment by k-doering-NOAA** [comment]
I think this hasn't been a problem, but we can reopen it in the future!
