### ISSUE TITLE
Spatial Closure App turns 'grey' after changing display closed area

### ISSUE THREAD

**Issue by jmlondon** [nmfs-opensci/nmfs-connect#9]
## requestor
Josh London josh.london@noaa.gov

## Which app were you testing?
decision support tool

## What were you trying to do?
change the initial setting for the 'display closed area'

## What did you experience?
as soon as I changed to menu, the screen went to grey

**Comment by k-doering-NOAA** [comment]
@jmlondon This is a pretty old issue so I'm closing - but feel free to re-open if we need to explore more.
